In [36]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

In [37]:
print a
print np.reshape(a, (1,5))


[1 2 3 4 5]
[[1 2 3 4 5]]


In [4]:
b

array([5, 4, 3, 2, 1])

In [5]:
np.add(a, b)

array([6, 6, 6, 6, 6])

In [6]:
np.subtract(a, b)

array([-4, -2,  0,  2,  4])

In [7]:
np.dot(a, b)

35

In [32]:
my_vector = np.array([1, 2, 3, 4, 5, 6])
my_matrix = np.reshape(my_vector, (2,3))

print my_vector
print my_matrix
print type(my_vector)
print type(my_matrix)
print my_vector.ndim
print my_matrix.ndim
print my_vector.shape
print my_matrix.shape

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
<type 'numpy.ndarray'>
<type 'numpy.ndarray'>
1
2
(6,)
(2, 3)


In [35]:
y = my_matrix.reshape(1,-1)
print y

[[1 2 3 4 5 6]]


In [38]:
a.dtype

dtype('int64')

In [39]:
zf = np.array([1,2,3,4,5.0])

In [40]:
zf.dtype

dtype('float64')

In [42]:
list_one = [1,3,5,7,9]
list_two = [2,4,6,8,10]

In [59]:
%%timeit
def dot_prod(a, b):
    total = 0
    for i in range(len(a)):
        mini_prod = a[i] * b[i]
        total += mini_prod
    return total

dot_prod(list_one, list_two)

The slowest run took 6.01 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 992 ns per loop


In [44]:
print np.dot(list_one, list_two)

190


In [57]:
%%timeit
sum([x*y for x,y in zip(list_one, list_two)])

The slowest run took 4.95 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.25 µs per loop


In [53]:
print zip(list_one, list_two)

[(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)]
