In [8]:
# import numpy

import numpy as np

# create array x

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [9]:
# print the shape of x

x.shape

(10,)

In [18]:
# create a two dimensional array
y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print y

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
# print shape of 2d array
y.shape

(4, 3)

In [21]:
# reshape the array to 2 x 6
y_new = np.reshape(y, (2,6))
print y_new

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [22]:
# reshape the array to 1 x 12
y_even_newer = np.reshape(y, (1, 12))
print y_even_newer

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [23]:
# transpose the array
y_t = np.reshape(y, (12, 1))
print y_t

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [8]:
# indexing method 1

In [9]:
# indexing method 2

In [13]:
# indexing method 3

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6